#!/bin/bash

# Salon Backend Deployment Helper
# Shows available deployment options

echo "🚀 Salon Backend Deployment Options"
echo "===================================="
echo ""
echo "📋 Quick Deploy Commands:"
echo ""
echo "1️⃣  Normal deployment (preserves database):"
echo "   ./update-and-deploy.sh"
echo "   ./update-and-deploy.sh --preserve-db"
echo ""
echo "2️⃣  Fresh deployment (cleans database):"
echo "   ./update-and-deploy.sh --clean-db"
echo ""
echo "3️⃣  Server-only deployment (preserves database):"
echo "   ./deploy-to-server.sh"
echo "   ./deploy-to-server.sh --preserve-db"
echo ""
echo "4️⃣  Server-only deployment (cleans database):"
echo "   ./deploy-to-server.sh --clean-db"
echo ""
echo "5️⃣  Quick one-command deploy (preserves database):"
echo "   ./one-command-deploy.sh"
echo "   ./one-command-deploy.sh --preserve-db"
echo ""
echo "6️⃣  Quick one-command deploy (cleans database):"
echo "   ./one-command-deploy.sh --clean-db"
echo ""
echo "📝 Notes:"
echo "   • Default behavior: PRESERVES database data"
echo "   • Use --clean-db only when you want to reset everything"
echo "   • Use --preserve-db to explicitly preserve data (redundant but clear)"
echo ""
echo "❓ For help on any script:"
echo "   ./script-name.sh --help"
echo ""
echo "🌐 After deployment, check:"
echo "   API: http://142.93.220.120:3000"
echo "   Health: http://142.93.220.120:3000/health"
echo "   Docs: http://142.93.220.120:3000/api"