export interface OtpSendResult {
  success: boolean;
  otp?: string; // OTP code if generated by provider
}

export interface IOtpProvider {
  /**
   * Send OTP to the specified phone number for a specific role
   * @param phone - Phone number to send OTP to
   * @param role - User role requesting OTP (optional for backward compatibility)
   * @returns Promise<boolean | OtpSendResult> - Success status or detailed result
   */
  sendOtp(phone: string, role?: string): Promise<boolean | OtpSendResult>;

  /**
   * Verify OTP for the specified phone number and role
   * @param phone - Phone number to verify
   * @param otp - OTP code to verify
   * @param role - User role for verification (optional for backward compatibility)
   * @returns Promise<boolean> - Verification success status
   */
  verifyOtp(phone: string, otp: string, role?: string): Promise<boolean>;

  /**
   * Get provider name for logging/identification
   * @returns string - Provider name
   */
  getProviderName(): string;
}

export enum OtpProviderType {
  CONSOLE = 'console',
  TWILIO = 'twilio',           // Modern Twilio Verify Service (recommended)
  TWILIO_SMS = 'twilio-sms',   // Legacy Twilio SMS (requires phone number)
  BHASHSMS = 'bhashsms',       // BhashSMS SMS provider
  AWS_SNS = 'aws-sns',
  FIREBASE = 'firebase',
}