-- ============================================================================
-- Migration: Add Arrival OTP to Booking Requests
-- Date: 2024-11-02
-- Description: Adds arrival OTP verification before payment to prevent no-shows
-- 
-- Changes:
--   1. Add 3 new columns for arrival OTP tracking
--   2. Add new status 'approved_otp_generated' to booking flow
--   3. Update status constraint to accept new value
--
-- Backward Compatible: YES (all columns nullable, existing data unaffected)
-- Zero Downtime: YES (can run while application is live)
-- ============================================================================

BEGIN;

-- ============================================================================
-- STEP 1: Add New Columns
-- ============================================================================

DO $$
BEGIN
    -- Add arrival_otp column
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'booking_requests' 
        AND column_name = 'arrival_otp'
    ) THEN
        ALTER TABLE booking_requests ADD COLUMN arrival_otp VARCHAR(6);
        RAISE NOTICE '[1/3] ✓ Added column: arrival_otp';
    ELSE
        RAISE NOTICE '[1/3] ⚠ Column arrival_otp already exists, skipping';
    END IF;

    -- Add arrival_otp_generated_at column
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'booking_requests' 
        AND column_name = 'arrival_otp_generated_at'
    ) THEN
        ALTER TABLE booking_requests ADD COLUMN arrival_otp_generated_at TIMESTAMP;
        RAISE NOTICE '[2/3] ✓ Added column: arrival_otp_generated_at';
    ELSE
        RAISE NOTICE '[2/3] ⚠ Column arrival_otp_generated_at already exists, skipping';
    END IF;

    -- Add arrival_otp_verified_at column
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'booking_requests' 
        AND column_name = 'arrival_otp_verified_at'
    ) THEN
        ALTER TABLE booking_requests ADD COLUMN arrival_otp_verified_at TIMESTAMP;
        RAISE NOTICE '[3/3] ✓ Added column: arrival_otp_verified_at';
    ELSE
        RAISE NOTICE '[3/3] ⚠ Column arrival_otp_verified_at already exists, skipping';
    END IF;
END $$;

-- ============================================================================
-- STEP 2: Add Documentation Comments
-- ============================================================================

COMMENT ON COLUMN booking_requests.arrival_otp IS 
    '6-digit OTP generated when business approves request, shown to customer, verified before payment';

COMMENT ON COLUMN booking_requests.arrival_otp_generated_at IS 
    'Timestamp when arrival OTP was generated by business owner approval';

COMMENT ON COLUMN booking_requests.arrival_otp_verified_at IS 
    'Timestamp when business owner verified customer arrival OTP before allowing payment';

DO $$
BEGIN
    RAISE NOTICE '✓ Added column documentation comments';
END $$;

-- ============================================================================
-- STEP 3: Update Status (Handle both ENUM and CHECK constraint)
-- ============================================================================

DO $$
DECLARE
    constraint_name text;
    enum_name text;
    column_type text;
    enum_exists boolean;
BEGIN
    -- Check if status column uses ENUM or CHECK constraint
    SELECT data_type INTO column_type
    FROM information_schema.columns
    WHERE table_name = 'booking_requests' AND column_name = 'status';

    IF column_type = 'USER-DEFINED' THEN
        -- Status uses ENUM type
        RAISE NOTICE '📋 Status column uses ENUM type';
        
        -- Get enum type name
        SELECT udt_name INTO enum_name
        FROM information_schema.columns
        WHERE table_name = 'booking_requests' AND column_name = 'status';
        
        -- Check if 'approved_otp_generated' already exists in enum
        SELECT EXISTS(
            SELECT 1 FROM pg_enum e
            JOIN pg_type t ON e.enumtypid = t.oid
            WHERE t.typname = enum_name
            AND e.enumlabel = 'approved_otp_generated'
        ) INTO enum_exists;
        
        IF NOT enum_exists THEN
            -- Add new value to enum (after 'pending')
            EXECUTE format('ALTER TYPE %I ADD VALUE IF NOT EXISTS ''approved_otp_generated'' AFTER ''pending''', enum_name);
            RAISE NOTICE '✓ Added approved_otp_generated to ENUM: %', enum_name;
        ELSE
            RAISE NOTICE '⚠ Value approved_otp_generated already exists in ENUM';
        END IF;
        
    ELSE
        -- Status uses CHECK constraint
        RAISE NOTICE '📋 Status column uses CHECK constraint';
        
        -- Find existing status constraint
        SELECT conname INTO constraint_name
        FROM pg_constraint
        WHERE conrelid = 'booking_requests'::regclass
        AND contype = 'c'
        AND pg_get_constraintdef(oid) LIKE '%status%'
        LIMIT 1;

        -- Drop old constraint if exists
        IF constraint_name IS NOT NULL THEN
            EXECUTE format('ALTER TABLE booking_requests DROP CONSTRAINT IF EXISTS %I', constraint_name);
            RAISE NOTICE '✓ Dropped existing constraint: %', constraint_name;
        ELSE
            RAISE NOTICE '⚠ No existing status constraint found';
        END IF;

        -- Create new constraint with all valid statuses
        ALTER TABLE booking_requests 
        ADD CONSTRAINT booking_requests_valid_status 
        CHECK (status IN (
            'pending',
            'approved_otp_generated',      -- NEW: Business approved, OTP sent to customer
            'approved_pending_payment',    -- NEW: Customer arrival verified, ready for payment
            'approved',                    -- Payment completed, booking confirmed
            'rejected'                     -- Rejected by business or cancelled by customer
        ));

        RAISE NOTICE '✓ Created new status constraint with approved_otp_generated';
    END IF;
END $$;

-- ============================================================================
-- STEP 4: Comprehensive Verification
-- ============================================================================

DO $$
DECLARE
    col_count integer;
    constraint_count integer;
    test_status text;
    all_checks_passed boolean := true;
BEGIN
    RAISE NOTICE '';
    RAISE NOTICE '========================================';
    RAISE NOTICE 'VERIFICATION RESULTS';
    RAISE NOTICE '========================================';

    -- Check 1: Verify all columns exist
    SELECT COUNT(*) INTO col_count
    FROM information_schema.columns
    WHERE table_name = 'booking_requests'
    AND column_name IN ('arrival_otp', 'arrival_otp_generated_at', 'arrival_otp_verified_at');

    IF col_count = 3 THEN
        RAISE NOTICE '✓ All 3 columns exist';
    ELSE
        RAISE WARNING '✗ Only % of 3 expected columns found', col_count;
        all_checks_passed := false;
    END IF;

    -- Check 2: Verify columns have correct data types
    SELECT COUNT(*) INTO col_count
    FROM information_schema.columns
    WHERE table_name = 'booking_requests'
    AND (
        (column_name = 'arrival_otp' AND udt_name = 'varchar' AND character_maximum_length = 6)
        OR (column_name = 'arrival_otp_generated_at' AND udt_name = 'timestamp')
        OR (column_name = 'arrival_otp_verified_at' AND udt_name = 'timestamp')
    );

    IF col_count = 3 THEN
        RAISE NOTICE '✓ All columns have correct data types';
    ELSE
        RAISE WARNING '✗ Some columns have incorrect data types';
        all_checks_passed := false;
    END IF;

    -- Check 3: Verify status constraint exists
    SELECT COUNT(*) INTO constraint_count
    FROM pg_constraint
    WHERE conrelid = 'booking_requests'::regclass
    AND conname = 'booking_requests_valid_status';

    IF constraint_count = 1 THEN
        RAISE NOTICE '✓ Status constraint exists';
    ELSE
        RAISE WARNING '✗ Status constraint not found';
        all_checks_passed := false;
    END IF;

    -- Check 4: Verify constraint accepts new status value
    BEGIN
        -- Try to validate constraint with new status
        PERFORM 1 FROM pg_constraint
        WHERE conrelid = 'booking_requests'::regclass
        AND conname = 'booking_requests_valid_status'
        AND pg_get_constraintdef(oid) LIKE '%approved_otp_generated%';
        
        IF FOUND THEN
            RAISE NOTICE '✓ Constraint includes approved_otp_generated status';
        ELSE
            RAISE WARNING '✗ Constraint does not include approved_otp_generated';
            all_checks_passed := false;
        END IF;
    END;

    -- Check 5: Verify comments exist
    SELECT COUNT(*) INTO col_count
    FROM pg_description d
    JOIN pg_class c ON d.objoid = c.oid
    JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = d.objsubid
    WHERE c.relname = 'booking_requests'
    AND a.attname IN ('arrival_otp', 'arrival_otp_generated_at', 'arrival_otp_verified_at')
    AND d.description IS NOT NULL;

    IF col_count = 3 THEN
        RAISE NOTICE '✓ All column comments exist';
    ELSE
        RAISE NOTICE '⚠ Only % of 3 column comments found', col_count;
    END IF;

    -- Final summary
    RAISE NOTICE '========================================';
    IF all_checks_passed THEN
        RAISE NOTICE '✓✓✓ MIGRATION COMPLETED SUCCESSFULLY ✓✓✓';
        RAISE NOTICE 'All critical checks passed!';
    ELSE
        RAISE WARNING '⚠⚠⚠ MIGRATION COMPLETED WITH WARNINGS ⚠⚠⚠';
        RAISE WARNING 'Some checks failed. Review warnings above.';
    END IF;
    RAISE NOTICE '========================================';
    RAISE NOTICE '';
    RAISE NOTICE 'Next Steps:';
    RAISE NOTICE '1. Deploy updated application code';
    RAISE NOTICE '2. Test arrival OTP flow end-to-end';
    RAISE NOTICE '3. Monitor logs for any errors';
    RAISE NOTICE '';
END $$;

COMMIT;

-- ============================================================================
-- ROLLBACK SCRIPT (DO NOT RUN - Keep for reference only)
-- ============================================================================
/*
BEGIN;

-- Remove arrival OTP columns
ALTER TABLE booking_requests
DROP COLUMN IF EXISTS arrival_otp,
DROP COLUMN IF EXISTS arrival_otp_generated_at,
DROP COLUMN IF EXISTS arrival_otp_verified_at;

-- Restore old status constraint
ALTER TABLE booking_requests 
DROP CONSTRAINT IF EXISTS booking_requests_valid_status;

ALTER TABLE booking_requests 
ADD CONSTRAINT booking_requests_valid_status 
CHECK (status IN (
    'pending',
    'approved_pending_payment',
    'approved',
    'rejected'
));

RAISE NOTICE 'Rollback completed';

COMMIT;
*/

-- ============================================================================
-- MANUAL VERIFICATION QUERIES (Run after migration)
-- ============================================================================
/*
-- 1. Check column details
SELECT 
    column_name, 
    data_type, 
    character_maximum_length,
    is_nullable 
FROM information_schema.columns 
WHERE table_name = 'booking_requests' 
AND column_name IN ('arrival_otp', 'arrival_otp_generated_at', 'arrival_otp_verified_at')
ORDER BY column_name;

-- 2. Check constraint details
SELECT 
    conname as constraint_name,
    pg_get_constraintdef(oid) as constraint_definition
FROM pg_constraint
WHERE conrelid = 'booking_requests'::regclass
AND conname = 'booking_requests_valid_status';

-- 3. Check existing data (should all be NULL for new columns)
SELECT 
    COUNT(*) as total_rows,
    COUNT(arrival_otp) as rows_with_arrival_otp,
    COUNT(arrival_otp_generated_at) as rows_with_generated_at,
    COUNT(arrival_otp_verified_at) as rows_with_verified_at
FROM booking_requests;

-- 4. Test constraint - should succeed
SELECT 'approved_otp_generated' IN (
    SELECT unnest(string_to_array(
        regexp_replace(
            pg_get_constraintdef(oid), 
            '.*\((.*)\).*', 
            '\1'
        ), 
        ', '
    ))
    FROM pg_constraint
    WHERE conrelid = 'booking_requests'::regclass
    AND conname = 'booking_requests_valid_status'
) as new_status_allowed;
*/
