export enum DocumentType {
  AADHAR = 'aadhar',
  PAN = 'pan',
  SHOP_ACT = 'shop_act',
  GST = 'gst',
  GST_CERTIFICATE = 'gst_certificate',
  UDYAM_AADHAAR = 'udyam_aadhaar',
  ID_PROOF = 'id_proof',
  ADDRESS_PROOF = 'address_proof',
  BUSINESS_LICENSE = 'business_license',
  TRADE_LICENSE = 'trade_license',
  FSSAI_LICENSE = 'fssai_license',
  MSME_REGISTRATION = 'msme_registration',
  BANK_STATEMENT = 'bank_statement',
  CANCELLED_CHEQUE = 'cancelled_cheque',
  ELECTRICITY_BILL = 'electricity_bill',
  RENT_AGREEMENT = 'rent_agreement',
  SHOP_PHOTO = 'shop_photo',
  PHOTOGRAPH = 'photograph',
  SIGNATURE = 'signature',
  PASSPORT_PHOTO = 'passport_photo',
  VOTER_ID = 'voter_id',
  DRIVING_LICENSE = 'driving_license',
  PASSPORT = 'passport',
  RATION_CARD = 'ration_card',
  INCOME_TAX_RETURN = 'income_tax_return',
  PROPERTY_TAX_RECEIPT = 'property_tax_receipt',
  WATER_BILL = 'water_bill',
  TELEPHONE_BILL = 'telephone_bill',
  INTERNET_BILL = 'internet_bill',
  INSURANCE_POLICY = 'insurance_policy',
  MEMORANDUM_OF_ASSOCIATION = 'memorandum_of_association',
  ARTICLES_OF_ASSOCIATION = 'articles_of_association',
  BOARD_RESOLUTION = 'board_resolution',
  PARTNERSHIP_DEED = 'partnership_deed',
  LLP_AGREEMENT = 'llp_agreement',
  TRUST_DEED = 'trust_deed',
  SOCIETY_REGISTRATION = 'society_registration',
  IMPORT_EXPORT_CODE = 'import_export_code',
  LABOR_LICENSE = 'labor_license',
  POLLUTION_CERTIFICATE = 'pollution_certificate',
  FIRE_SAFETY_CERTIFICATE = 'fire_safety_certificate',
  HEALTH_LICENSE = 'health_license',
  WEIGHTS_AND_MEASURES = 'weights_and_measures',
  LEGAL_HEIR_CERTIFICATE = 'legal_heir_certificate',
  NOC_CERTIFICATE = 'noc_certificate',
  COMPLETION_CERTIFICATE = 'completion_certificate',
  OCCUPANCY_CERTIFICATE = 'occupancy_certificate',
  BUILDING_PLAN_APPROVAL = 'building_plan_approval',
  OTHER = 'other',
}

export enum DocumentStatus {
  PENDING = 'pending',
  VERIFIED = 'verified',
  REJECTED = 'rejected',
}
